version: '3.8'
services:
  app:
    build: .
    container_name: treadlogic-app
    restart: always
    ports:
      - "8100:8090"
    environment:
      - API_TOKEN=${API_TOKEN}
    volumes:
      # Монтируем ТОМ в папку data внутри контейнера
      - treadlogic_data:/app/data

# Объявляем том (Docker создаст его сам)
volumes:
  treadlogic_data: